### ISSUE TITLE
Missing thumb7em-none-eabi.json?

### ISSUE THREAD

**Issue by heathkit** [jamesmunns/teensy3-rs-demo#5]
Thanks for the exciting project! I'm trying to get it running on my Teensy, but when I do `make flash` I get the error.

```
error: no target specification file found for thumbv7em-none-eabi
note: run with `RUST_BACKTRACE=1` for a backtrace
make: *** [build] Error 1
zsh: exit 2     make flash
```

Also, the instructions seem to mention `thumb7em-none-eabi.json'. Is it missing? Sorry, I'm new to Rust, so I might be missing something.

**Comment by heathkit** [comment]
Ah, nevermind, I got it. You guys aren't kidding when you say use Rust nightly.

**Comment by jamesmunns** [comment]
@mgiambalvo Hey! No worries. Glad you figured it out. Let me know if you have any other issues!
